# Configurer l'environnement "go" en spécifiant : la version du dependabot, le répertoire, quand dependabot vérifie les maj et type de dépendance à mettre à jour.

---
version: 2
updates:
  - package-ecosystem: "gomod"
 directory: "/"
schedule:
 interval: "daily"
allow:
 - dependency-type: "direct"
 update-type: "semver:minor"



# Configurer le docker pour le fichier dependabot-actions.
---
version: 2
updates:
 - package-ecosystem: "docker"
 directory: "/"
 schedule:
  interval: "daily"