name: dependabot

#configuration du dependabot pour l'execution à 1 h du matin chaque jours.
on:
  schedule:
    - cron: "0 1 * * *"

#création d'un job pour le dependabot et utilisation du SE ubuntu.
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      # récuperer le code du repo git, préciser la version pour le checkout et configurer l'environnement de travail.
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
      # exécuter le dependabot en précisant le token d'accès au GitHub.
      - name: Dependabot
        uses: dependabot/dependabot-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
