name: Test Workflow

#déclancer le workflow à chaque push pour les tests du projet.
on:
  push:

#définir la version go pour l'exécution des tests.
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]

#utiliser la version 3 et le SE ubuntu, installer la version go avec setup-go et configurer la commande go test ./... pour exécuter les tests.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      run: go test ./...